/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vishwa
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fname = new javax.swing.JButton();
        lname = new javax.swing.JButton();
        dob = new javax.swing.JButton();
        pass = new javax.swing.JButton();
        phno = new javax.swing.JButton();
        city = new javax.swing.JButton();
        state = new javax.swing.JButton();
        pincode = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fname.setText("FIRST NAME");
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 150, 30));

        lname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lname.setText("LAST NAME");
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 160, 30));

        dob.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dob.setText("DOB");
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 150, 30));

        pass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pass.setText("PASSWORD");
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 150, 30));

        phno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phno.setText("PHONE");
        phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnoActionPerformed(evt);
            }
        });
        getContentPane().add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 150, 30));

        city.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        city.setText("CITY");
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 150, 30));

        state.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        state.setText("STATE");
        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        getContentPane().add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 150, 30));

        pincode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pincode.setText("PINCODE");
        pincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincodeActionPerformed(evt);
            }
        });
        getContentPane().add(pincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 150, 30));

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setText("BACK");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATE DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 230, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/full2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
        try{
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/votingsystem","root","Vishwa4746");
                String query1="update voters set first_name=? where voter_id=?";
                PreparedStatement  s1=con.prepareStatement(query1);
                String voterid=Login.voter.getText();
                s1.setString(2, voterid);
                String fname=JOptionPane.showInputDialog(null,"enter new first name" );
                s1.setString(1,fname);
                s1.executeUpdate();
                JOptionPane.showMessageDialog(null,"first name updated");
            }
        catch (SQLException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
            
        
    }//GEN-LAST:event_fnameActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Homepage jf2=new Homepage();
        jf2.show();
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
         try{
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/votingsystem","root","Vishwa4746");
                String query1="update voters set last_name=? where voter_id=?";
                PreparedStatement  s1=con.prepareStatement(query1);
                String voterid=Login.voter.getText();
                s1.setString(2, voterid);
                String lname=JOptionPane.showInputDialog(null,"enter new last name" );
                s1.setString(1,lname);
                s1.executeUpdate();
                JOptionPane.showMessageDialog(null,"last name updated");
            }
        catch (SQLException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_lnameActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
        try{
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/votingsystem","root","Vishwa4746");
                String query1="update voters set dob=? where voter_id=?";
                PreparedStatement  s1=con.prepareStatement(query1);
                String voterid=Login.voter.getText();
                s1.setString(2, voterid);
                String dob=JOptionPane.showInputDialog(null,"enter new DOB yyyy-mm-dd" );
                s1.setString(1,dob);
                s1.executeUpdate();
                JOptionPane.showMessageDialog(null,"dob updated");
            }
        catch (SQLException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_dobActionPerformed

    private void phnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnoActionPerformed
        // TODO add your handling code here:
        try{
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/votingsystem","root","Vishwa4746");
                String query1="update voters set phno=? where voter_id=?";
                PreparedStatement  s1=con.prepareStatement(query1);
                String voterid=Login.voter.getText();
                s1.setString(2, voterid);
                String phno=JOptionPane.showInputDialog(null,"enter new phone number" );
                s1.setString(1,phno);
                s1.executeUpdate();
                JOptionPane.showMessageDialog(null,"phone number updated");
            }
        catch (SQLException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_phnoActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
        try{
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/votingsystem","root","Vishwa4746");
                String query1="update voters set password=? where voter_id=?";
                PreparedStatement  s1=con.prepareStatement(query1);
                String voterid=Login.voter.getText();
                s1.setString(2, voterid);
                String password=JOptionPane.showInputDialog(null,"enter new password" );
                s1.setString(1,password);
                s1.executeUpdate();
                JOptionPane.showMessageDialog(null,"password updated");
            }
        catch (SQLException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_passActionPerformed

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
        try{
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/votingsystem","root","Vishwa4746");
                String query1="update voters set state=? where voter_id=?";
                PreparedStatement  s1=con.prepareStatement(query1);
                String voterid=Login.voter.getText();
                s1.setString(2, voterid);
                String state=JOptionPane.showInputDialog(null,"enter new state" );
                s1.setString(1,state);
                s1.executeUpdate();
                JOptionPane.showMessageDialog(null,"state updated");
            }
        catch (SQLException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_stateActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
        try{
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/votingsystem","root","Vishwa4746");
                String query1="update voters set city=? where voter_id=?";
                PreparedStatement  s1=con.prepareStatement(query1);
                String voterid=Login.voter.getText();
                s1.setString(2, voterid);
                String city=JOptionPane.showInputDialog(null,"enter new city" );
                s1.setString(1,city);
                s1.executeUpdate();
                JOptionPane.showMessageDialog(null,"city updated");
            }
        catch (SQLException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_cityActionPerformed

    private void pincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincodeActionPerformed
        // TODO add your handling code here:
        try{
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/votingsystem","root","Vishwa4746");
                String query1="update voters set pincode=? where voter_id=?";
                PreparedStatement  s1=con.prepareStatement(query1);
                String voterid=Login.voter.getText();
                s1.setString(2, voterid);
                String pincode=JOptionPane.showInputDialog(null,"enter new pincode" );
                s1.setString(1,pincode);
                s1.executeUpdate();
                JOptionPane.showMessageDialog(null,"pincode updated");
            }
        catch (SQLException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex){
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_pincodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton city;
    private javax.swing.JButton dob;
    private javax.swing.JButton fname;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton lname;
    private javax.swing.JButton pass;
    private javax.swing.JButton phno;
    private javax.swing.JButton pincode;
    private javax.swing.JButton state;
    // End of variables declaration//GEN-END:variables
}
